### ISSUE TITLE
bioSyntax TODO

### ISSUE THREAD

**Issue by ababaian** [bioSyntax/bioSyntax#2]
A collection of tasks to improve bioSyntax. Feel free to tackle any of these if you'd like to pitch in.

### Features

- [ ] Add Atomic Coloring. [JMol](http://jmol.sourceforge.net/jscolors/) / [CPK](https://en.wikipedia.org/wiki/CPK_coloring) coloring to atoms/elements when they appear in a file-format (PDB).

- [ ] Set-up Vim / Sublime / Gedit to only use bioSyntax theme when a bioSyntax format is being used; otherwise use the default or preset theme. [Sublime Example](https://hiltmon.com/blog/2012/11/07/multiple-themes-in-sublime-text-2/)

- [ ] Re-write the `bed-gedit` syntax to use ['Robust Column Selection'](https://github.com/ababaian/bioSyntax/issues/17)

- [ ] Optimize the Regex Engine for VCF -gedit -sublime -vim(?) to account for catastrophic backtracking. (See vcf-less for a fixed example)

- [ ] Secondary Color Gradient: In BED/WIG files where there can be a score, have one color scheme (like we have) for 0-1000 range. Have a second color gradient (orange?) which recognizes 0.0 - 1.00 (decimal scale). This will support two widely used data-ranges then 0-1 and 0-1000.

- [ ] Make 'Infographics' for complex file-types (SAM, VCF, GTF) to help users learn and intepret the file formats. Include things such as PHRED numeric scale, FLAG conversion bits, what each field is etc... Use bioSyntax theme colours as a teaching tool here.

### Installer Updates:
- [ ] For less: inform user and prompt (Y/N) for software updates and adding alias commands
- [ ] On website, include an uninstall instructions. (i.e. delete these files)

### New File Format Support
- See: [File Format Matrix](https://github.com/bioSyntax/bioSyntax/issues/1)

**Comment by ababaian** [comment]
# Completed Tasks

- [x] 3) Re-write the `bed-gedit` syntax to use ['Robust Column Selection'](https://github.com/ababaian/bioSyntax/issues/17) [Jeff]

- [x] 12) sam-less. In the sequence section, if the chromosome/contig contains "-" characters, it throws off the column index. Fix regex selection. [ Artem TALL].

### Installer beta3 updates:
- [x] For less: inform user and prompt (Y/N) for software updates and adding alias commands
- [x] Remove all `sudo` commands which are not absolutely necessary. (Vim installs should be sudo-free). 
- [x] On website, include an uninstall instructions. (i.e. delete these files)
- [x] Check sublime install paths in the install script. See: [commit](https://github.com/bioSyntax/bioSyntax/commit/6a69fafb3008f155172186e7826ff524fa6e6817)
